### ISSUE TITLE
/loadTAS not working

### ISSUE THREAD

**Issue by Iris7395** [MinecraftTAS/TASmod#210]
https://github.com/user-attachments/assets/52fdc5dd-7ba7-4c74-8ad7-333a9b7bf593

how to replicate
1. save macro with name
2. load macro with name
3. there the command will not work anymore

**Comment by Iris7395** [comment]
it also doesnt work even tho i do the "bye_dream" normally i saw the video type "bye_dream."

**Comment by ScribbleTAS** [comment]
Wow, great catch...
Normally the commands are `/load` `/save`, but I have set up command aliases that also allow for `/saveTAS`... And I can't remember why, but I wrote loadTAS in the readme...

Turns out, I forgot to set up the alias for loadTAS...  
I never use that command, I only use `/load`

So yeah, a workaround for this is to use `/load`
