### ISSUE TITLE
not teleporting to correct location

### ISSUE THREAD

**Issue by Iris7395** [MinecraftTAS/TASmod#212]
https://github.com/user-attachments/assets/f2930656-eb24-470a-9f1b-ce60cd897633

[latest.log](https://github.com/user-attachments/files/16201869/latest.log)
here is log to if it will help

**Comment by Iris7395** [comment]
it was supposed to teleport somewhere but then it teleported me somewhere else rather than the original location

**Comment by ScribbleTAS** [comment]
@Iris7395 Please use the newest builds for testing (Always available under the [actions](https://github.com/MinecraftTAS/TASmod/actions/workflows/buildandupload.yml) tab on GitHub):
[TASmod-Dev-Build.zip](https://github.com/user-attachments/files/16201902/TASmod-Dev-Build.zip)

The mod is now on Legacy-Fabric instead of Forge: https://legacyfabric.net/

**Comment by Iris7395** [comment]
oh ok i downloaded the nerw build everything seems fine
